### ISSUE TITLE
Installation error after homebrew install

### ISSUE THREAD

**Issue by AntonKL** [natemcmaster/dnvm#1]
Using environment 'default'
System.UnauthorizedAccessException: Access to the path '/usr/local/share/dnvm/environments/default' is denied. ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at System.IO.UnixFileSystem.CreateDirectory(String fullPath)
   at System.IO.Directory.CreateDirectory(String path)
   at DotNet.VersionManager.Commands.InstallCommandBase.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DotNet.VersionManager.Program.<RunAsync>d__8.MoveNext()

**Comment by natemcmaster** [comment]
So, first of all, kudos @AntonKL for being the first person to discover this project. This was an experiment I did about a year ago. I haven't worked on it lately, but was thinking it might be time to try again.

The default location for environments is /usr/local/share/dnvm/. A better fix would be to change this to $HOME/.dnvm if /usr/local/share/dnvm/ is not writable, but for now, you should be able to workaround like this.
```
sudo mkdir -p /usr/local/share/dnvm/
sudo chown -R $(whoami) /usr/local/share/dnvm/ 
```
Let me know if that helps

**Comment by ericnograles** [comment]
I guess that makes me second! 😆 

I actually had to execute the following commands to get everything copacetic @AntonKL:

```bash
sudo mkdir -p /usr/local/share/dnvm/
sudo chown -R $(whoami) /usr/local/share/dnvm/ 
mkdir -p /usr/local/share/dnvm/environments
mkdir -p /usr/local/share/dnvm/environments/default
```

Seriously, good stuff though @natemcmaster, this will be invaluable for me as I get reacquainted with .Net after years in the JavaScript jungle.

I'll try to PR back a fix to write to `$HOME/.dnvm`, like how NVM works, later this week.

**Comment by ericnograles** [comment]
Actually @natemcmaster looks like there may have been something missing in the brew install, as `dnvm` is an unrecognized command:

![image](https://user-images.githubusercontent.com/6023705/35768227-83b49790-08c6-11e8-8e7d-9abacd6f4ddf.png)

I usually run `zsh`, but I tried in normal `bash` with the same effect. Is there something we need to drop in our `~/.zshrc` or `~/.bash_profile` to get this working properly?

**Comment by ericnograles** [comment]
Nevermind, @natemcmaster I see multiple version of .Net core can coexist with the new CLI. My apologies, got some catching up to do in this ecosystem!

**Comment by natemcmaster** [comment]
Yes, dotnet already supports having multiple versions of the SDK and multiple runtimes installed. However, it does not provide good mechanisms for installing those automatically. This project was an experiment in developing a UX similar to nvm and rvm for dotnet. I never got around to making everything truly work and ran out of steam.

@AntonKL @ericnograles I'm curious what led you here. How did you find the project? Is this something you would like to actually use? Is it worth considering starting up this project again?

**Comment by ericnograles** [comment]
@natemcmaster tbh I'm walking into the .Net Core ecosystem blind. I slung "classic" .Net way back 5 years ago, but had since abandoned it in favor of "universal" JavaScript with Node.js on the server-side and various technologies on the client side (mainly React and React Native, but also fiddling with Vue). I figured I'd get reacquainted with my old friends C# and ASP .Net to see how the DX was for non-Windows machines these days, as well as to check out Azure for cloud native apps.

That being said, I basically Googled `.net version manager`, as my local setup for universal JS usually consists of [Node Version Manager](https://github.com/creationix/nvm) because Node does not natively allow for multiple versions to be concurrently installed.

I definitely think there may be value in picking this project up again, especially for installs of the SDK using bash and cmd. At the very least, it might push .Net core to support it natively. 

The reason is that universal installers for dev tools are generally mistrusted imo.  I think that's the reason why I didn't even think to check if .Net Core natively supported concurrent versions -- I've been working with tools like Java, Python, and Node.js for so long that I forgot that concurrent versions of .Net weren't a big deal. Non .Net installers have a pretty bad rep of nuking your local versions and generally making a mess of things (looking at you, Python 😆 ), which require tools like nvm, rvm, or pyenv.

**Comment by natemcmaster** [comment]
haha, i'm surprised this showed up in google's results.

well, maybe i'll dust this project off a little and get it going again. 

It appears the IOException had something to do with High Sierra. The issue went away when I upgraded dnvm to use .NET Core 1.1.6 and pushed out dnvm 0.1.2. Try updating via homebrew and let me know it if works for you.

    brew upgrade dnvm

**Comment by natemcmaster** [comment]
Should be fixed. Let me know if you still have trouble.
